### ISSUE TITLE
paper request!

### ISSUE THREAD

**Issue by raysun0501** [qilong-zhang/Patch-wise-iterative-attack#1]
Blogger, can you supply your paper link or paper full text of this source code?
I want to read your project attentively. 
Thanks.

**Comment by qilong-zhang** [comment]
@RaySunWHUT Hi，since our paper is still under revision, we have only uploaded the temporary version. You can download from this repo (`6114-temporary version.pdf`).

**Comment by raysun0501** [comment]
Oh, yes. I saw it. Thank you and congratulations!
