### ISSUE TITLE
Where is the pdf file of the paper?

### ISSUE THREAD

**Issue by machanic** [qilong-zhang/Patch-wise-iterative-attack#2]

**Comment by qilong-zhang** [comment]
![image](https://user-images.githubusercontent.com/30571468/86862520-efc1c800-c0fb-11ea-882a-d55843594671.png)
@machanic  Hi, the pdf is here

**Comment by qilong-zhang** [comment]
@machanic hi, we have uploaded the paper in ArXiv, you can find [here](https://arxiv.org/abs/2007.06765).  If there is no other question, please close this issue, thanks~
