### ISSUE TITLE
Comparison with SOTA

### ISSUE THREAD

**Issue by Muzammal-Naseer** [qilong-zhang/Patch-wise-iterative-attack#3]
Hi,

Congratulation on your ECCV paper. I wonder how the transferability of your attack compared with this work (Cross-Domain Transferability of Adversarial Perturbations (https://arxiv.org/abs/1905.11736))?

This is the state-of-the-art attack in terms of transferability.

**Comment by qilong-zhang** [comment]
@Muzammal-Naseer  
Hi,

Thanks for your attention. In our paper, we focus on FGSM-based attack methods. So we don't consider generator-oriented perturbations. But the results of your paper "Cross-Domain Transferability of Adversarial Perturbations" is really impressive (e.g., Tab 6, the reported result is better than DTPI-FGSM).

I hope we can communicate more in the future. I am particularly interested in your method.

**Comment by Muzammal-Naseer** [comment]
Hi, 

Sure, we can have a discussion. Feel free to contact me.

**Comment by qilong-zhang** [comment]
Thanks~
