### ISSUE TITLE
Discrepancy between the code and the paper 

### ISSUE THREAD

**Issue by ZhengyuZhao** [qilong-zhang/Patch-wise-iterative-attack#5]
Hi! Nice to see such an interesting paper with code released.

I have a question about your Pytorch code.

In line 100 (x = x + alpha_beta * torch.sign(noise) + projection) of the script "project_iter_attack.py", from what I understand, here the added perturbations are actually bounded within (-32,32) instead of (-16,16), since both the "alpha_beta * torch.sign(noise)" and "projection" are bounded by 16.
I have run the code and confirmed that this is indeed 32 but not 16.

However, as shown in line 12 of the pseudo-code in your paper, there is a clipping operation to bound the perturbations into (-16,16). So I add this line and obviously get much worse results than the MI-FGSM method. (63.9% vs. 83.8%, when transferring from resnet50 to densenet121).

Could you please help me with this discrepancy? Thanks!

**Comment by ZhengyuZhao** [comment]
sorry, I misunderstood your code

**Comment by qilong-zhang** [comment]
@ZhengyuZhao Thank you for your interest in our work, feel free to ask any question you may want to know~
