### ISSUE TITLE
Hyper parameter setting

### ISSUE THREAD

**Issue by hcguoO0** [qilong-zhang/Patch-wise-iterative-attack#6]
Your paper is interesting.
I have a question about your code. In your paper, you point out that β = 2.5, γ = 2 for DMPI-FGSM.
But I found the result is bad when running your code with such parameter setting, and β = 10, γ = 16 for DMPI-FGSM seems to achieve good performance.
So  I would like to make sure whether the setting is right in your paper.

**Comment by qilong-zhang** [comment]
Hi @ghcdgit , I have checked my code and hyperparameter settings of Tab.1, the result shows that β = 2.5, γ = 2 for DMPI-FGSM is right. Following is my hyperparameter settings:
```
- P_kern, kern_size = project_kern(3)
- alpha_beta = alpha * 2.5
- gamma = alpha_beta * 0.5
```

**Comment by hcguoO0** [comment]
thank you, it indeed has good performance following your setting.
And my mistake is to set gamma = 2 directly, I wonder why this has so different performance, can you help me to explain this? thanks.

**Comment by qilong-zhang** [comment]
Noted that our inputs are normalized to [-1, 1], therefore, max perturbation eps should also be normalized by
```
eps = 2.0 * FLAGS.max_epsilon / 255.0
```
so in this case, gamma should not be set to 2 directly

**Comment by hcguoO0** [comment]
I am too careless, thanks
