### ISSUE TITLE
Why I can't use ens_adv_inception_resnet_v2 checkpoint to load model

### ISSUE THREAD

**Issue by 201700800201** [qilong-zhang/Patch-wise-iterative-attack#7]

**Comment by 201700800201** [comment]
![image](https://user-images.githubusercontent.com/50281991/147440055-f8467d74-5035-4ef2-bbec-653f865a78d1.png)

**Comment by qilong-zhang** [comment]
@201700800201 hello, have you solved this issue?

**Comment by 201700800201** [comment]
你好，想请教一下，就是我在加载ens_adv_inception_resnet_v2模型的时候，利用官方给的权重，修改了checkpoint路径为ens_adv_inception_resnet_v2.ckpt，但是运行时发现说权重key找不到，这个问题该如何解决呀



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qilong ***@***.***&gt;; 
发送时间: 2021年12月27日(星期一) 下午2:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qilong-zhang/Patch-wise-iterative-attack] Why I can&#39;t use ens_adv_inception_resnet_v2 checkpoint to load model (Issue #7)





 
@201700800201 hello, have you solved this issue?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qilong-zhang** [comment]
> 你好，想请教一下，就是我在加载ens_adv_inception_resnet_v2模型的时候，利用官方给的权重，修改了checkpoint路径为ens_adv_inception_resnet_v2.ckpt，但是运行时发现说权重key找不到，这个问题该如何解决呀
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Qilong ***@***.***&gt;; 发送时间: 2021年12月27日(星期一) 下午2:20 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [qilong-zhang/Patch-wise-iterative-attack] Why I can&#39;t use ens_adv_inception_resnet_v2 checkpoint to load model (Issue #7) @201700800201 hello, have you solved this issue? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

**Comment by qilong-zhang** [comment]
其他模型都可以加载吗？只有这个加载不了吗？

**Comment by 201700800201** [comment]
是的，根据你们提供tf版本的代码，里面需要的5个模型，就这个权重加载不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qilong ***@***.***&gt;; 
发送时间: 2021年12月27日(星期一) 下午2:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qilong-zhang/Patch-wise-iterative-attack] Why I can&#39;t use ens_adv_inception_resnet_v2 checkpoint to load model (Issue #7)





 
其他模型都可以加载吗？只有这个加载不了吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qilong-zhang** [comment]
https://github.com/tensorflow/models/tree/master/research/slim#Pretrained 你是从这边下载的吗？ 
或者你可以考虑用pytroch来写代码（比tf好用），我们也有转好的模型，可以从这获取：https://github.com/ylhz/tf_to_pytorch_model

**Comment by 201700800201** [comment]
好的好的，我试试别的模型，谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qilong ***@***.***&gt;; 
发送时间: 2021年12月27日(星期一) 下午5:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [qilong-zhang/Patch-wise-iterative-attack] Why I can&#39;t use ens_adv_inception_resnet_v2 checkpoint to load model (Issue #7)





 
https://github.com/tensorflow/models/tree/master/research/slim#Pretrained 你是从这边下载的吗？
 或者你可以考虑用pytroch来写代码（比tf好用），我们也有转好的模型，可以从这获取：https://github.com/ylhz/tf_to_pytorch_model
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by BiiiGerrr** [comment]
我遇到了同样的问题，似乎是因为ens_adv_inception_resnet_v2_2017_08_18.tar.gz 解压出来后有
 .meta 
.index 
.data-00000-of-00001 
三个后缀的文件， 直接读取.ckpt不能使用， 请问作者是怎么操作的？

**Comment by qilong-zhang** [comment]
> 我遇到了同样的问题，似乎是因为ens_adv_inception_resnet_v2_2017_08_18.tar.gz 解压出来后有 .meta .index .data-00000-of-00001 三个后缀的文件， 直接读取.ckpt不能使用， 请问作者是怎么操作的？

你试试看MI-FGSM官方仓库给的[模型链接](http://ml.cs.tsinghua.edu.cn/~yinpeng/nips17/nontargeted/models.zip)

**Comment by BiiiGerrr** [comment]
> > 我遇到了同样的问题，似乎是因为ens_adv_inception_resnet_v2_2017_08_18.tar.gz 解压出来后有 .meta .index .data-00000-of-00001 三个后缀的文件， 直接读取.ckpt不能使用， 请问作者是怎么操作的？
> 
> 你试试看MI-FGSM官方仓库给的[模型链接](http://ml.cs.tsinghua.edu.cn/~yinpeng/nips17/nontargeted/models.zip)

tf的问题还是无法解决，不过我已经通过您的pytorch版本进行了评测，十分感谢您的贡献。

此外，我对DI算法和您的PI进行了评测。发现DI在指标上会略高于PI方法。  
考虑到由于数据集可能不相同的原因，这是正常的吗？  我选取了Imagenet val 5000张可以被识别的图像，以及相同的DI指标p=0.7  以及步长=1.6。在源模型resnet152上生成样本进行了测试，发现对于正常模型 DI的迁移性高于PI， 而在防御模型上，PI表现更好。

**Comment by qilong-zhang** [comment]
> > > 我遇到了同样的问题，似乎是因为ens_adv_inception_resnet_v2_2017_08_18.tar.gz 解压出来后有 .meta .index .data-00000-of-00001 三个后缀的文件， 直接读取.ckpt不能使用， 请问作者是怎么操作的？
> > 
> > 
> > 你试试看MI-FGSM官方仓库给的[模型链接](http://ml.cs.tsinghua.edu.cn/~yinpeng/nips17/nontargeted/models.zip)
> 
> tf的问题还是无法解决，不过我已经通过您的pytorch版本进行了评测，十分感谢您的贡献。
> 
> 此外，我对DI算法和您的PI进行了评测。发现DI在指标上会略高于PI方法。 考虑到由于数据集可能不相同的原因，这是正常的吗？ 我选取了Imagenet val 5000张可以被识别的图像，以及相同的DI指标p=0.7 以及步长=1.6。在源模型resnet152上生成样本进行了测试，发现对于正常模型 DI的迁移性高于PI， 而在防御模型上，PI表现更好。

应该是合理的，我的论文中当替代模型是ResNet时，有时候DI也比PI好。此外注意PI在迁移到普通模型和防御模型时参数是不一致的。
